version: '3.9'

networks:
  shaktiblog:
    driver: bridge

volumes:
  shaktiblog_db:
  shaktiblog_data:

services:
  web:
    build: .
    container_name: shaktiblog
    ports: ["8001:8000"]
    command: >
      sh -c "python3 manage.py makemigrations && python3 manage.py migrate &&
        python3 manage.py runserver 0.0.0.0:8000"
    environment:
      DATABASE_URL: "postgres://postgres:ShaktiDB123@db:5432/shaktiblog"
      DOMAIN_ALIASES: "localhost, 127.0.0.1, ap.shakticoin.com"
      DB_HOST: "db"
      DB_NAME: "shaktiblog"
      DB_USER: "postgres"
      DB_PASS: "ShaktiDB123"
    volumes:
      - shaktiblog_data:/usr/src/app
    depends_on:
      - db
    networks:
      - shaktiblog
    dns:
      - 8.8.8.8
      - 4.4.4.4

  db:
    image: postgres:13-alpine
    container_name: shaktiblog_db
    environment:
      POSTGRES_DB: "shaktiblog"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "ShaktiDB123"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "5432:5432"
    restart: always
    networks:
      - shaktiblog
    volumes:
      - shaktiblog_db:/var/lib/postgresql/data"
