version: '3.9'

networks:
  shaktiblog_net:
    name: shaktiblog_net
    driver: bridge

volumes:
  shaktiblog_db:
  shaktiblog_data:

services:
  web:
    #build: .
    image: $FULL_IMAGE_NAME
    container_name: shaktiblog
    ports: ["8001:8000"]
    #command: ping 8.8.8.8
    command: >
      sh -c "python3 manage.py makemigrations && python3 manage.py migrate &&
        python3 manage.py runserver 0.0.0.0:8000"
    environment:
      DATABASE_URL: "postgres://postgres:ShaktiDB123@db:5432/shaktiblog"
      DOMAIN_ALIASES: "localhost, 127.0.0.1, ap.shakticoin.com"
      DB_HOST: "shaktiblog-django-database.cqocxpwhlloo.us-east-2.rds.amazonaws.com"
      DB_NAME: "shaktiblog"
      DB_USER: "postgres"
      DB_PASS: "vEuV2p!Su6=Wwxm&"
    volumes:
      - shaktiblog_data:/usr/src/app
    networks:
      - shaktiblog_net
    dns:
      - 8.8.8.8
      - 4.4.4.4

