# Generated by Django 4.0.3 on 2022-04-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap_news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='ap_wire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='moreimages_apnews',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='moreimages_apwire',
            name='image',
            field=models.ImageField(upload_to='media/', verbose_name='Image'),
        ),
    ]
