# Generated by Django 4.0.3 on 2022-03-22 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='role',
        ),
        migrations.CreateModel(
            name='UserTableConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Writer', 'Writer'), ('Editor', 'Editor'), ('Publisher', 'Publisher'), ('Approver', 'Approver')], max_length=20, null=True)),
                ('tables', multiselectfield.db.fields.MultiSelectField(choices=[('APWire_Content_Pitching', 'APWire_Content_Pitching'), ('APWire_Writing_Rewrite', 'APWire_Writing_Rewrite')], max_length=46)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
