# Generated by Django 4.0.3 on 2022-03-22 07:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_usercustom_role_usertableconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertableconnection',
            name='tables',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('APWire_Content_Pitching', 'APWire_Content_Pitching'), ('APWire_Writing_Rewrite', 'APWire_Writing_Rewrite'), ('apwire_ReviewDraft1', 'apwire_ReviewDraft1'), ('apwire_ReviewDraft2', 'apwire_ReviewDraft2'), ('apews_FDNApproval', 'apews_FDNApproval'), ('apnews_ReadyForRelease', 'apnews_ReadyForRelease'), ('apnews_APPublished', 'apnews_APPublished')], max_length=146),
        ),
    ]
