# Generated by Django 4.0.3 on 2022-04-08 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ap_news_ap_wire_category_permissions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
