# Generated by Django 4.0.3 on 2022-05-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ap_news_image_alter_ap_wire_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ap_news',
            name='blog_release_status',
            field=models.CharField(choices=[('test', 'test'), ('test', 'test2')], default='test', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ap_wire',
            name='blog_release_status',
            field=models.CharField(choices=[('test', 'test'), ('test', 'test2')], default='test', max_length=30),
            preserve_default=False,
        ),
    ]
