# Generated by Django 4.0.4 on 2022-06-27 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mangeimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangeimages',
            options={'verbose_name_plural': 'manage image'},
        ),
    ]
