# Generated by Django 4.0.3 on 2022-04-12 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_permissions_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap_news',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ap_wire',
            name='published_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
