# Generated by Django 4.0.3 on 2022-03-22 09:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usertableconnection_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('status', models.CharField(choices=[('Content_Pitching', 'Content_Pitching'), ('Writing_Rewrite', 'Writing_Rewrite'), ('ReviewDraft1', 'ReviewDraft1'), ('ReviewDraft2', 'ReviewDraft2'), ('FDNApproval', 'FDNApproval'), ('ReadyForRelease', 'ReadyForRelease'), ('APPublished', 'APPublished')], max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='apews_FDNApproval',
        ),
        migrations.DeleteModel(
            name='apnews_APPublished',
        ),
        migrations.DeleteModel(
            name='apnews_ContentPitching',
        ),
        migrations.DeleteModel(
            name='apnews_ReadyForRelease',
        ),
        migrations.DeleteModel(
            name='apnews_ReviewDraft1',
        ),
        migrations.DeleteModel(
            name='apnews_ReviewDraft2',
        ),
        migrations.DeleteModel(
            name='apnews_WritingRewrite',
        ),
        migrations.DeleteModel(
            name='apwire_APPublished',
        ),
        migrations.DeleteModel(
            name='apwire_ContentPitching',
        ),
        migrations.DeleteModel(
            name='apwire_FDNApproval',
        ),
        migrations.DeleteModel(
            name='apwire_ReadyForRelease',
        ),
        migrations.DeleteModel(
            name='apwire_ReviewDraft1',
        ),
        migrations.DeleteModel(
            name='apwire_ReviewDraft2',
        ),
        migrations.DeleteModel(
            name='apwire_WritingRewrite',
        ),
        migrations.AlterField(
            model_name='usertableconnection',
            name='tables',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('APWire_Content_Pitching', 'APWire_Content_Pitching'), ('APWire_Writing_Rewrite', 'APWire_Writing_Rewrite'), ('apwire_ReviewDraft1', 'apwire_ReviewDraft1'), ('apwire_ReviewDraft2', 'apwire_ReviewDraft2'), ('FDNApproval', 'FDNApproval'), ('ReadyForRelease', 'ReadyForRelease'), ('APPublished', 'APPublished')], max_length=126),
        ),
    ]
