# Generated by Django 3.2.14 on 2022-07-08 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_mangeimages_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ap_news',
            name='downloadstatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ap_wire',
            name='downloadstatus',
            field=models.BooleanField(default=False),
        ),
    ]
