# Generated by Django 4.0.3 on 2022-05-10 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ap_news_blog_release_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog_progress_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Blog Progress Status',
            },
        ),
        migrations.AlterField(
            model_name='ap_news',
            name='blog_release_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blog_progress_status'),
        ),
        migrations.AlterField(
            model_name='ap_wire',
            name='blog_release_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.blog_progress_status'),
        ),
    ]
