# Generated by Django 3.2.14 on 2022-07-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220708_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='AP_flag',
            field=models.BooleanField(default=False),
        ),
    ]
