# Generated by Django 4.0.3 on 2022-05-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_blog_progress_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_progress_status',
            options={'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='blog_progress_status',
            name='name',
            field=models.CharField(choices=[('Draft', 'Draft'), ('in Progress', 'in Progress'), ('Completed', 'Completed')], max_length=100),
        ),
    ]
