# Generated by Django 4.0.3 on 2022-04-14 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_content_brief'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='content_brief',
            options={'verbose_name_plural': 'Content Brief'},
        ),
        migrations.AlterField(
            model_name='ap_news',
            name='status',
            field=models.CharField(choices=[('Content_Pitching', 'Story Pitching'), ('Writing_Rewrite', 'Writing & Rewriting'), ('Review_Draft_1', 'First Review'), ('Review_Draft_2', 'Second Review'), ('FDN_Approval_1', 'Ready For FDN Approval'), ('Ready_For_Release', 'Ready For Release'), ('App_Published', 'AP Published')], default='APNews_Content_Pitching', max_length=30),
        ),
        migrations.AlterField(
            model_name='ap_wire',
            name='status',
            field=models.CharField(choices=[('Content_Pitching', 'Story Pitching'), ('Writing_Rewrite', 'Writing & Rewriting'), ('Review_Draft_1', 'First Review'), ('Review_Draft_2', 'Second Review'), ('FDN_Approval_1', 'Ready For FDN Approval'), ('Ready_For_Release', 'Ready For Release'), ('App_Published', 'AP Published')], default='APWire_Content_Pitching', max_length=30),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='status',
            field=models.CharField(choices=[('Content_Pitching', 'Story Pitching'), ('Writing_Rewrite', 'Writing & Rewriting'), ('Review_Draft_1', 'First Review'), ('Review_Draft_2', 'Second Review'), ('FDN_Approval_1', 'Ready For FDN Approval'), ('Ready_For_Release', 'Ready For Release'), ('App_Published', 'AP Published')], max_length=20),
        ),
        migrations.CreateModel(
            name='moreimages_apwire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.ap_wire')),
            ],
        ),
        migrations.CreateModel(
            name='moreimages_apnews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.ap_wire')),
            ],
        ),
    ]
