# Generated by Django 4.0.3 on 2022-05-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_blog_progress_status_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_progress_status',
            name='name',
            field=models.CharField(choices=[('Draft', 'Draft'), ('in Progress', 'in Progress'), ('Completed', 'Completed')], default='in Progress', max_length=100),
        ),
    ]
