# Generated by Django 4.0.3 on 2022-03-22 09:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_blog_delete_apews_fdnapproval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='apews_FDNApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apnews_APPublished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apnews_ContentPitching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apnews_ReadyForRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apnews_ReviewDraft1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apnews_ReviewDraft2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apnews_WritingRewrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apwire_APPublished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apwire_ContentPitching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apwire_FDNApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apwire_ReadyForRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apwire_ReviewDraft1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apwire_ReviewDraft2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='apwire_WritingRewrite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='type',
        ),
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Content_Pitching', 'Content_Pitching'), ('Writing_Rewrite', 'Writing_Rewrite'), ('ReviewDraft1', 'ReviewDraft1'), ('ReviewDraft2', 'ReviewDraft2'), ('FDNApproval', 'FDNApproval'), ('ReadyForRelease', 'ReadyForRelease'), ('APPublished', 'APPublished')], default='APWire_Content_Pitching', max_length=30),
        ),
    ]
