# Generated by Django 4.0.3 on 2022-04-19 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_options_alter_content_brief_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moreimages_apnews',
            options={'verbose_name_plural': 'AP-News Images'},
        ),
        migrations.AlterModelOptions(
            name='moreimages_apwire',
            options={'verbose_name_plural': 'AP-Wire Images'},
        ),
        migrations.AlterField(
            model_name='moreimages_apnews',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.ap_news'),
        ),
        migrations.AlterField(
            model_name='permissions',
            name='status',
            field=models.CharField(choices=[('Content_Pitching', 'Story Pitching'), ('Writing_Rewrite', 'Writing & Rewriting'), ('Review_Draft_1', 'First Review'), ('Review_Draft_2', 'Second Review'), ('FDN_Approval_1', 'Ready For FDN Approval'), ('Ready_For_Release', 'Ready For Release'), ('App_Published', 'AP Published')], max_length=20, unique=True),
        ),
    ]
