# Generated by Django 4.0.3 on 2022-05-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_blog_progress_status_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap_news',
            name='blog_release_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('in Progress', 'in Progress'), ('Completed', 'Completed')], default='in Progress', max_length=30),
        ),
        migrations.AlterField(
            model_name='ap_wire',
            name='blog_release_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('in Progress', 'in Progress'), ('Completed', 'Completed')], default='in Progress', max_length=30),
        ),
        migrations.DeleteModel(
            name='blog_progress_status',
        ),
    ]
