# Generated by Django 4.0.3 on 2022-03-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_apews_fdnapproval_apnews_appublished_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='apews_FDNApproval',
        ),
        migrations.DeleteModel(
            name='apnews_APPublished',
        ),
        migrations.DeleteModel(
            name='apnews_ContentPitching',
        ),
        migrations.DeleteModel(
            name='apnews_ReadyForRelease',
        ),
        migrations.DeleteModel(
            name='apnews_ReviewDraft1',
        ),
        migrations.DeleteModel(
            name='apnews_ReviewDraft2',
        ),
        migrations.DeleteModel(
            name='apnews_WritingRewrite',
        ),
        migrations.DeleteModel(
            name='apwire_APPublished',
        ),
        migrations.DeleteModel(
            name='apwire_ContentPitching',
        ),
        migrations.DeleteModel(
            name='apwire_FDNApproval',
        ),
        migrations.DeleteModel(
            name='apwire_ReadyForRelease',
        ),
        migrations.DeleteModel(
            name='apwire_ReviewDraft1',
        ),
        migrations.DeleteModel(
            name='apwire_ReviewDraft2',
        ),
        migrations.DeleteModel(
            name='apwire_WritingRewrite',
        ),
    ]
