# Generated by Django 4.0.3 on 2022-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_ap_news_blog_release_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap_news',
            name='blog_release_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='In progress', max_length=30),
        ),
        migrations.AlterField(
            model_name='ap_wire',
            name='blog_release_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('In progress', 'In progress'), ('Completed', 'Completed')], default='In progress', max_length=30),
        ),
    ]
