# Generated by Django 4.0.3 on 2022-03-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_delete_apews_fdnapproval_delete_apnews_appublished_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='APPublished',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Writer', 'Writer'), ('Editor', 'Editor'), ('Publisher', 'Publisher'), ('Approver', 'Approver')], default='Writer', max_length=20),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='Content_Pitching',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Writer', 'Writer'), ('Editor', 'Editor'), ('Publisher', 'Publisher'), ('Approver', 'Approver')], default='Writer', max_length=20),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='FDNApproval',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Writer', 'Writer'), ('Editor', 'Editor'), ('Publisher', 'Publisher'), ('Approver', 'Approver')], default='Writer', max_length=20),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='ReadyForRelease',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Writer', 'Writer'), ('Editor', 'Editor'), ('Publisher', 'Publisher'), ('Approver', 'Approver')], default='Writer', max_length=20),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='ReviewDraft1',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Writer', 'Writer'), ('Editor', 'Editor'), ('Publisher', 'Publisher'), ('Approver', 'Approver')], default='Writer', max_length=20),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='ReviewDraft2',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Writer', 'Writer'), ('Editor', 'Editor'), ('Publisher', 'Publisher'), ('Approver', 'Approver')], default='Writer', max_length=20),
        ),
        migrations.AddField(
            model_name='usercustom',
            name='Writing_Rewrite',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Writer', 'Writer'), ('Editor', 'Editor'), ('Publisher', 'Publisher'), ('Approver', 'Approver')], default='Writer', max_length=20),
        ),
    ]
