# Generated by Django 4.0.3 on 2022-03-24 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_blog_status_blog2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
