# Generated by Django 4.0.3 on 2022-03-25 06:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_blog_image_alter_blog2_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=300),
        ),
    ]
