# Generated by Django 4.0.3 on 2022-03-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_blog_publishedon_blog2_publishedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publishedon',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='publishedon',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='status',
            field=models.CharField(choices=[('Content_Pitching', 'Content_Pitching'), ('Writing_Rewrite', 'Writing_Rewrite'), ('Review_Draft_1', 'Review_Draft_1'), ('Review_Draft_2', 'Review_Draft_2'), ('FDN_Approval_1', 'FDN_Approval_1'), ('Ready_For_Release', 'Ready_For_Release'), ('App_Published', 'App_Published')], default='APNews_Content_Pitching', max_length=30),
        ),
    ]
