# Generated by Django 4.0.3 on 2022-03-28 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_blog_unique_id_blog2_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publishedon',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='publishedon',
            field=models.DateField(auto_now_add=True),
        ),
    ]
