# Generated by Django 4.0.3 on 2022-03-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_blog_publishedon_alter_blog2_publishedon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='publishedon',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog2',
            name='publishedon',
            field=models.DateField(blank=True, null=True),
        ),
    ]
