# Generated by Django 4.0.3 on 2022-04-01 11:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_usercustom_accessint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog2',
            new_name='Ap_News',
        ),
        migrations.RenameModel(
            old_name='Blog',
            new_name='Ap_Wire',
        ),
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Content_Pitching', 'Content_Pitching'), ('Writing_Rewrite', 'Writing_Rewrite'), ('Review_Draft_1', 'Review_Draft_1'), ('Review_Draft_2', 'Review_Draft_2'), ('FDN_Approval_1', 'FDN_Approval_1'), ('Ready_For_Release', 'Ready_For_Release'), ('App_Published', 'App_Published')], max_length=20)),
                ('create', models.BooleanField(default=False)),
                ('edit', models.BooleanField(default=False)),
                ('view', models.BooleanField(default=False)),
                ('move', models.BooleanField(default=False)),
                ('publish', models.BooleanField(default=False)),
                ('to_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
