# Generated by Django 4.0.3 on 2022-04-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_blog2_ap_news_rename_blog_ap_wire_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ap_news',
            options={'verbose_name_plural': 'Ap-News'},
        ),
        migrations.AlterModelOptions(
            name='ap_wire',
            options={'verbose_name_plural': 'Ap-Wire'},
        ),
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name_plural': 'Permissions'},
        ),
        migrations.AddField(
            model_name='permissions',
            name='Permission_Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
