# Generated by Django 4.0.3 on 2022-04-04 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_ap_news_options_alter_ap_wire_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='user',
            new_name='UserCustom',
        ),
    ]
