# Generated by Django 4.0.3 on 2022-04-04 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_user_permissions_usercustom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='UserCustom',
            new_name='user',
        ),
    ]
