# Generated by Django 4.0.3 on 2022-04-05 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_usercustom_permissions_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='APPublished',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='Content_Pitching',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='FDNApproval',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='ReadyForRelease',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='ReviewDraft1',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='ReviewDraft2',
        ),
        migrations.RemoveField(
            model_name='usercustom',
            name='Writing_Rewrite',
        ),
    ]
