# Generated by Django 4.0.3 on 2022-04-05 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_remove_usercustom_appublished_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustom',
            name='accessint',
        ),
    ]
