# Generated by Django 4.0.3 on 2022-04-05 05:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_usercustom_accessint'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustom',
            name='accessint',
            field=models.IntegerField(blank=True, default=7, null=True, validators=[django.core.validators.MaxValueValidator(limit_value=7), django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
