# Generated by Django 4.0.3 on 2022-04-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_usercustom_accessint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ap_news',
            options={'verbose_name_plural': 'AP-News'},
        ),
        migrations.AlterModelOptions(
            name='ap_wire',
            options={'verbose_name_plural': 'AP-Wire'},
        ),
        migrations.AlterField(
            model_name='ap_news',
            name='topic',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='ap_wire',
            name='topic',
            field=models.CharField(max_length=200),
        ),
    ]
