# Generated by Django 4.0.3 on 2022-04-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_ap_news_options_alter_ap_wire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ap_news',
            name='reverted_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ap_wire',
            name='reverted_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
