# Generated by Django 4.0.3 on 2022-04-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_ap_news_reverted_count_ap_wire_reverted_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap_news',
            name='reverted_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ap_wire',
            name='reverted_count',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
