# Generated by Django 4.0.3 on 2022-04-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_alter_ap_news_reverted_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap_news',
            name='reverted_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ap_wire',
            name='reverted_count',
            field=models.IntegerField(default=1),
        ),
    ]
